lancaster-university/codal-microbit-v2

inc/compat/mbed.h
`mbed.h` will only be included by files that don't know about CODAL, right?
=> #define Timer MbedTimer

inc/Mixer2.h, source/MicroBitAudio.cpp, source/Mixer2.cpp
Changed variable sampleRate to float to avoid rounding errors when generating frequencies so that tones played via the microbit v2 internal speaker are now more accurate to the target frequency, during testing only 0.1-0.4hz out, which could be due to innacuracy in the detection equipment.
Additionally, manually set the mixer2 sample rate to 44100 in the microbit audio enable function. Some experinentation could be done here to match the sample rate to the true output from the PWM and observe if this improves accuracy futher.
This pull request mirrors and relies on lancaster-university/codal-nrf52 repo of the same name
=> Fixing Inaccurate notes produced on Micro:bit v2

resources/logfs/dl.js
If the 1s timeout hadn't passed then we'll be reinstating the wrong
text for subsequent events, easy to trigger with a double click.
No change to the C++ resource as this feature is in the online HTML
only.
See https://github.com/lancaster-university/codal-microbit-v2/issues/110#issuecomment-859475124
=> Can't use original text as might still be "Copied"

inc/bluetooth/MicroBitBLEManager.h, model/MicroBit.cpp, source/bluetooth/MicroBitBLEManager.cpp
This fixes:
- master branch stops on wake-up with panic 070 once paired
- power down should be blocked while BLE is connected
- advertising is restarted on wake-up
Test program compiled with microbit-v2-samples and this branch of codal-microbit-v2: [MICROBIT.zip](https://github.com/lancaster-university/codal-microbit-v2/files/7656634/MICROBIT.zip)
It's possible to connect with the iOS micro:bit app monitor and see accelerometer readings, with power down suspended while connected. The button code below (A=>sleep; B=>wake and stay awake for 20s) is redundant with the timer.
main.cpp
```
#include "MicroBit.h"
MicroBit uBit;
void onClickA(MicroBitEvent)
{
uBit.power.deepSleep();
}
void onClickB(MicroBitEvent)
{
uBit.power.powerDownDisable();
uBit.display.image.setPixelValue( 4, 0, 255); …
```
=> Fix MicroBitBLEManager support for MicroBitPowerManager::deepSleep 

source/MicroBitUSBFlashManager.cpp
A bit inconsequential as the data read back is not being used, but the interface firmware is meant to send back the same number of bytes that was written to it.
=> Minor fix to read back the right amount of I2C data from the interface MCU.

resources/logfs/dl.js
Fixes issue https://github.com/lancaster-university/codal-microbit-v2/issues/143.
A simple one in the online JS, basically if the log is empty and the user clicks on "Visual Preview" it showed an `Unknown error` or `The visual preview requires two or more columns. Timestamps must be enabled.`
So, with this PR it will show the expected message `No data to graph.`.
=> datalog htm: Fix unintuitive error msg when trying to plot with empty data.

inc/MicroBitError.h, source/MicroBitAccelerometer.cpp, source/MicroBitCompass.cpp
Added a new error class which uses PanicCode as a base for Micro:bit v2 specific errors, and implemented these in the Accel and Compass classes.
This addresses the case where a damaged accel/compass module would cause a board to panic on boot, effectively bricking the device even if the user code never touches the peripheral.
See also:
- https://github.com/lancaster-university/codal-core/pull/151
- https://github.com/lancaster-university/codal-microbit-v2/issues/213
- https://github.com/lancaster-university/codal-microbit-v2/issues/191
=> Added soft-failure modes for the accelerometer and compass to prevent panic-on-boot issues

source/MicroBitLog.cpp
MicroBitLog now only checks the version string preamble, to avoid bugs where old logs are not detected during an erase cycle.
This effectively just checks the first 14 bytes of `MICROBIT_LOG_VERSION` aka `UBIT_LOG_FS_V_` such that a log written with `...001` is still detected as present by code running with `...002`, and will still be erased during a reflash, for example.
=> Modification to MICROBIT_LOG_VERSION checks for _isPresent() calls

inc/NRF52LedMatrix.h, source/NRF52LedMatrix.cpp
Implements NRF52LEDMatrix::rotateTo. Demo hex: [HelloRotate.zip](https://github.com/lancaster-university/codal-microbit-v2/files/9485105/HelloRotate.zip)
```
#include "MicroBit.h"
MicroBit uBit;
void setRotationForGesture( uint16_t gesture)
{
switch ( gesture)
{
case MICROBIT_ACCELEROMETER_EVT_TILT_UP:
uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_0);
break;
case MICROBIT_ACCELEROMETER_EVT_TILT_RIGHT:
uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_90);
break;
case MICROBIT_ACCELEROMETER_EVT_TILT_DOWN:
uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_180);
break;
case MICROBIT_ACCELEROMETER_EVT_TILT_LEFT:
uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_270);
break;
}
}
void onGesture( MicroBitEvent e)
{
switch ( e.value)
{
case MICROBIT_ACCELEROMETER_EVT_TILT_UP:
case …
```
=> NRF52LEDMatrix::rotateTo

model/MicroBit.h
The `@note` and `@code` is copy-pasted from the DAL docstrings.
This also removes the `@return` info as this is a void method.
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/150.
=> docstrings: Add granularity info to MicroBit::sleep() & remove return.

inc/compat/MicroBitSerial.h, source/compat/MicroBitSerial.cpp
The `CODAL_SERIAL_IN_USE` macro does not exist, the `codal-core` `Serial::redirect()` method returns `DEVICE_SERIAL_IN_USE` instead.
https://github.com/lancaster-university/codal-core/blob/a45ede432a646a0af86fbd89d9dd692689fb6fbd/source/driver-models/Serial.cpp#L842
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/238
=> docstrings: Minor fix in documented define name.

inc/bluetooth/MicroBitBLEManager.h, model/MicroBit.cpp, source/MicroBitPowerManager.cpp, source/bluetooth/MicroBitBLEManager.cpp
Before PR #114 the string was "BBC micro:bit V2.0", with that PR it was updated to indicate "BBC micro:bit V2.0" for board ID 0x9904 and "V2.X" to any unknown board ID (currently V2.2 boards would still appear as "V2.X").
There is no need for BLE apps or devices to distinguish between different V2 versions, just as we currently don't differentiate between V1.3 and V1.5.
Hardcoding this in CODAL to be "BBC micro:bit V2" also removes an I2C call to the interface chip on uBit.init(), which help us better support unofficial interface chip firmwares, like Segger's J-Link.
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/208
Related to https://github.com/lancaster-university/codal-microbit-v2/issues/137
=> Simplify the BLE - Device Info - Model Number to only indicate V2.

.github/workflows/build.yml
This workflow clones `lancaster-university/microbit-v2-samples` and edits to `codal.json` file to use the trigger commit.
It then builds the default project and the `ble_test()` as done in the microbit-v2-samples CI.
=> CI: Add build workflow using microbit-v2-samples.

.github/workflows/build.yml, .github/workflows/size-diff.yml
This PR uses Google's Bloaty McBloatface to analyse the MICROBIT elf file for memory consumption.
It also builds the PR base commit, or the commit parent, to do a diff and see the additional memory consumed or saved.
In the case of being a PR from a branch in this repository (not forks) it will post the diff as a comment as well.
To show an example diff in this PR (instead of an output just showing "no change in size"), the initial commit will contain a bit of code in MicroBit.cpp to create a 4000 byte array and a loop to write some data into it. So, the first bot comment will show the PR as increasing the `.bss` and `.text` sections.
I will then force push an update removing this code and the bot will post another comment showing a zero size increase. 
Both bloaty analysis outputs are …
=> CI: Add workflow to calculate build size diff before & after PR/commit.

.github/workflows/micropython.yml
As it only builds on pushes the PR doesn't produce a build, but this build from my fork can be seen as an example:
https://github.com/microbit-carlos/codal-microbit-v2/actions/runs/4196282038
=> CI: Build MicroPython on each commit.

.github/workflows/makecode.yml
Doesn't deploy anything, just checks that it can build the targets correctly (DAL, CODAL, with and without BLE).
One job builds with the Docker image defined in `pxt-microbit/pxtarget.json` and another job with the locally installed toolchain.
This workflow needs a secret to be added to the repo named `YOTTA_GITHUB_AUTHTOKEN` with a **read-only** fine grained token.
=> CI: Build MakeCode (with and without docker) on each commit.

.github/workflows/size-diff.yml
With this update to the Bloaty CI workflow we can trigger runs online via the GitHub website.
For example, once this PR is merged, to compare the main branch HEAD with the v0.2.43 commit (5785bb0), we can go to the Bloaty workflow view and trigger a new run with this form:
https://github.com/lancaster-university/codal-microbit-v2/actions/workflows/size-diff.yml
And it will calculate size difference between that commit and the main branch HEAD.
To show what that would look like we can have a look at this run from my fork: https://github.com/microbit-carlos/codal-microbit-v2/actions/runs/4295091495
=> CI: Enable manual triggers for size diff workflow.

.github/workflows/makecode.yml
Currently the MakeCode workflow is failing because a yotta dependency has been updated and subdependencies had clashes with pip version requirements.
=> CI: Restrict Python dep versions as workaround to pip install errors.

.github/workflows/build.yml, .github/workflows/micropython.yml, .github/workflows/size-diff.yml
Needed for this PR (which will stay as a draft PR for the time being):
- https://github.com/lancaster-university/codal-microbit-v2/pull/291
But can be merged immediately, as it's a good CI update to have in the main branch anyway.
=> CI: Ensure necessary repos are cloned with submodules.

model/MicroBit.cpp
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/331
=> Fix BLE panic 071

source/MicroBitCompassCalibrator.cpp
See https://github.com/lancaster-university/codal-microbit-v2/issues/286#issuecomment-1484223018
=> MicroBitCompassCalibrator - avoid using max(int,int)

.github/workflows/micropython.yml
Is not necessary and as MicroPython contains a lot of submodules with SDKs and similar it takes a long time to pull submodules recursively.
With this change CI build time goes down from 8 to 1 minute.
=> CI MicroPython: Don't checkout submodules recursively.

.github/workflows/size-diff.yml
New additions to the samples repo that use newer APIs will cause build failures in the "size diff" workflow, as it might be configured to compile an older versions of CODAL without those APIs.
This is currently the case, as new asserts have been added to CODAL and the samples repo, so any comparison with older CODAL tags will fail.
So, this PR adds another entry to the form to optionally specify a samples repo commit (bottom one in this screenshot):
=> CI: Update size diff workflow to let you configure the samples commit.

.github/workflows/makecode.yml
As mentioned in:
- https://github.com/lancaster-university/codal-microbit-v2/issues/338#issuecomment-1658767316
=> CI: Temporarily disable pxt docker build until image becomes available.

inc/MicroBitAccelerometer.h, inc/MicroBitCompass.h, source/MicroBitAccelerometer.cpp, source/MicroBitCompass.cpp, source/MicroBitDevice.cpp
In summary, when a motion sensor was not working, the `autoDetect()` function was returning a reference to a null pointer.
In this case it looks like the compiler must have been automatically generating the `codal::Accelerometer` and `codal::Compass` copy constructors, and instances of those generic parent classes would end up as `uBit.accelerometer` & `uBit.compass`.
With this PR we are returning an instance of `MicroBitAccelerometer` and `MicroBitCompass`, capable to throw a panic on first usage. Instances of these classes were never included in the builds before, which explains the large size increase for this PR.
The simplest update to these classes increased the build by almost 1KB, but the PR has been slimmed down to try to keep the build small. We'll see in the GitHub Actions PR …
=> Fix issue when missing motion sensor was crashing instead of panicking.

inc/MicroBitRadio.h, source/MicroBitRadio.cpp
As discussed in:
- https://github.com/lancaster-university/codal-microbit-v2/issues/260
This change more closely matches the input values for `MicroBitRadio::setTransmitPower()` that micro:bit V1 DAL has, so code trying to achieve the max possible value (`uBit.radio.setTransmitPower(7)`) works correctly in both V1 & V2.
I'll leave the PR in draft state until the discussion in https://github.com/lancaster-university/codal-microbit-v2/issues/260 is completed.
=> radio: Reduce power level options to match V1 DAL.

source/bluetooth/MicroBitBLEManager.cpp
Saw this when looking at https://github.com/lancaster-university/codal-microbit-v2/issues/370, it's a small change that results in the same string, but it saves a bit of flash with gcc v10.3.
The bloatly CI workflow should post here the size diff.
The `modelVersion` instance is not used anywhere else, `disName` results in the same string and is not used anywhere else either.
=> BLE: Simplify device name string creation.

.github/workflows/build.yml, .github/workflows/micropython.yml, .github/workflows/on-release.yml, .github/workflows/size-diff.yml, .github/workflows/update-changelog.yml
Warnings example:
https://github.com/lancaster-university/codal-microbit-v2/actions/runs/8066928871
=> CI: Update versions of actions to remove warnings about node 16.

inc/SoundEmojiSynthesizer.h
As per the title, just a set of definitions for downstream languages to use.
=> Added definitions to match the Makecode effects parameters

.github/tools/gitchanges.py, Changelog.md
It also changes the log format, as `git shortlog` groups the commits by author (or other options, but they always have to grouped) and that can get a bit verbose when also including commits from the other libraries.
Also, an advantage of not grouping by author is that the commits are listed historically.
As part of this PR I've also updated the changelog from v0.2.63, as this is the last tag used for MakeCode live, so it'll be useful to have this info when presenting MS the changelog for deployment.
=> Update Changelog script to include changes in lib dependencies.

model/MicroBit.cpp
@finneyj this would be the simplest way set the io.logo pin capacitive, do you think it should be behind a build flag as well? If so, what would be the best name for it? `MICROBIT_PIN_LOGO_CAPACITIVE`?
In that case we would still like to make sure the default value is set to capacitive, so the flag would be mostly used to disable this feature?
=> Set `uBit.io.logo` to capacitive touch mode by default.

.github/workflows/makecode.yml
A workaround needed for:
- https://github.com/microsoft/pxt-microbit/issues/5721
However, once GH update the Docker version inside the runner images we might need to figure out if the docker version can be downgraded.
=> CI: PXT build workaround due to deprecated PXT docker image type.

inc/MicroBitConfig.h, inc/MicroBitDevice.h, source/MicroBitDevice.cpp, target-locked.json
This PR required the latest commit from codal-core from PR:
- https://github.com/lancaster-university/codal-core/pull/169
And with these two PRs we can get the following defines and function outputs:
```
CODAL_VERSION_MAJOR: 0
CODAL_VERSION_MINOR: 2
CODAL_VERSION_PATCH: 66
CODAL_VERSION_HASH: 8c8db00
CODAL_TARGET_NAME: codal-microbit-v2
CODAL_VERSION: 0.2.66
CODAL_VERSION_LONG: 0.2.66+codal-microbit-v2-8c8db00
DEVICE_DAL_VERSION: 0.2.66
MICROBIT_DAL_VERSION: 0.2.66
microbit_dal_version(): 0.2.66
uBit.getVersion(): 0.2.66
```
=> Populate `MICROBIT_DAL_VERSION` and add `microbit_dal_version()`.

source/FSCache.cpp
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/406
With this program, FUL is in the HTM file, and LOG FULL appears, only after this change. 
```
#include "MicroBit.h"
MicroBit uBit;
int main() {
uBit.init();
uBit.display.print("?");
while (true) {
uBit.log.logString("1234567890,1234567890,1234567890,1234567890,1234567890\n");
uBit.sleep(1);
if (uBit.log.isFull()) {
uBit.display.print("D");
uBit.sleep(100);
}
}
}
```
=> Allow log full FUL to be written to last byte

target-locked.json, target.json
This is to workaround an issue in the iOS app as described in:
- https://github.com/microsoft/pxt-microbit/issues/5913
Versions with this patch:
```
CODAL_VERSION_MAJOR: 0
CODAL_VERSION_MINOR: 2
CODAL_VERSION_PATCH: 67
CODAL_VERSION_HASH: a8470a7
CODAL_TARGET_NAME: codal-microbit-v2
CODAL_VERSION: unknown
CODAL_VERSION_LONG: unknown+codal-microbit-v2-a8470a7
DEVICE_DAL_VERSION: unknown
MICROBIT_DAL_VERSION: unknown
microbit_dal_version(): unknown
uBit.getVersion(): unknown
```
=> Temporarily set CODAL_VERSION back to "unknown".

source/SoundSynthesizerEffects.cpp
I assume this was a simple typo, but since it didn't use the `PI` macro either, I just wanted to double check in case it wasn't @finneyj.
=> Fix Pi value typo.

.github/workflows/build.yml
MakeCode builds use an older GCC version, so we need to make sure any changes remain compatible.
```
$ docker run --rm -it pext/yotta:latest arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 6.2.1 20161205 (release) [ARM/embedded-6-branch revision 243739]
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
=> CI: Reduce the min GCC version used to match what MakeCode (PXT) uses.

source/MicroBitAudio.cpp
Fixes https://github.com/lancaster-university/codal-microbit-v2/issues/451
=> Update MicroBitAudio.isPlaying() to take into account initial silence.

target-locked.json, target.json
If we decide to merge this CODAL build system feature, this is how to activate it:
- https://github.com/lancaster-university/microbit-v2-samples/pull/81
Discussions are probably better over that PR.
=> Add 'show_size' option to target.json file to print build size info.

.github/workflows/makecode.yml, .github/workflows/micropython.yml
The main issue we had before is that on PRs GitHub creates a merge commit of the PR branch merged into main, and that git commit is not really pushed anywhere. So, when MicroPython and MakeCode try to git clone codal-microbit-v2 they get a git sha that does not exit in the upstream repo.
In MicroPython this is solved by using the action/checkout into the MicroPython codal/libraries folder.
In MakeCode it is solved by checking if the workflow is run from a PR, and in that case it just clones the PR branch, not the merge commit. That does mean that the MakeCode workflow does not run the test in the merge commit, but at least we'll have the results from the submitter's branch state.
=> ci: Also build MakeCode & MicroPython on PRs.

inc/MicroBitDevice.h, target-locked.json
Adds noreturn attribute to microbit_panic(), to prevent gcc warning about missing returns in various functions that use panic.
Adds "--param=min-pagesize=0" to gcc compiler flags, to prevent gcc warning about dereferencing hardcoded pointers near address 0.
=> eliminate compiler warnings

source/MicroBitCompassCalibrator.cpp, source/SoundExpressions.cpp, source/SoundSynthesizerEffects.cpp
Related PR, which includes files in codal-core like `LevelDetectorSPL`, and together with this PR it saves >400 bytes of flash:
- https://github.com/lancaster-university/codal-core/pull/176
_Edit: Also ensured float literals in a couple of other files to avoid implicit double promotion._
=> Ensure float operations in `SoundSynthesizerEffects` & `CompassCalibrator`.
